routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// public

Route::get('/', function () {
    return view('welcome');
});

// user

Auth::routes();
Route::get('register/verify/{token}', 'Auth\RegisterController@verify'); 

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('/profile',['as' => 'profile', 'uses' => 'ProfileController@index']);
Route::get('/profile/edit',['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);

Route::get('/password',['as' => 'password.index', 'uses' => 'ProfileController@change']);
Route::post('/password',['as' => 'password.post', 'uses' => 'ProfileController@post']);


Route::resource('data', 'DataController');
Route::get('/getIndex',['as' => 'data.getIndex', 'uses' => 'DataController@getIndex']);

// Gambar to base64
Route::resource('gambar', 'GambarController');

resources/views/home.blade.php
@extends('layouts.app')


@section('head')

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">

@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
                     @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
            <div class="panel panel-default">
                <div class="panel-heading">Data</div>
                <div class="panel-body">
                <a href="{{route('data.create')}}" class="btn btn-primary" style="float: right"><i class="fa fa-plus" aria-hidden="true"></i> Tambah</a>
                </div>
                <div class="panel-body">
                    <div class="box-body table-responsive">
                      <table id="data" class="display" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Judul</th>
                                <th>Keterangan</th>
                                <th>Dibuat</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>No</th>
                                <th>Judul</th>
                                <th>Keterangan</th>
                                <th>Dibuat</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footer')

<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

<script>
$(function() {

    $('#data').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('data.getIndex') !!}',
        columns: [
            { data: 'DT_Row_Index', name: 'DT_Row_Index',orderable: false, searchable: false },
            { data: 'judul', name: 'judul' },
            { data: 'keterangan', name: 'keterangan' },
            { data: 'created_at', name: 'created_at',orderable: false, searchable: false },
            { data: 'action', name: 'action',orderable: false, searchable: false }

        ],
    });
});
</script>

@endsection