routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// public

Route::get('/', function () {
    return view('welcome');
});

// user

Auth::routes();
Route::get('register/verify/{token}', 'Auth\RegisterController@verify'); 

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('/profile',['as' => 'profile', 'uses' => 'ProfileController@index']);
Route::get('/profile/edit',['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);

Route::get('/password',['as' => 'password.index', 'uses' => 'ProfileController@change']);
Route::post('/password',['as' => 'password.post', 'uses' => 'ProfileController@post']);


Route::resource('data', 'DataController');
Route::get('/getIndex',['as' => 'data.getIndex', 'uses' => 'DataController@getIndex']);

// Gambar to base64
Route::resource('gambar', 'GambarController');

app/Http/Controllers/GambarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GambarController extends Controller
{
    public function index()
    {
    	return view('gambar.index')->with(['data'=>"hasil"]);
    }

    public function store(Request $request)
    {
    	$gambar = $request->file('gambar');
    	$gambar_encode = base64_encode(file_get_contents($gambar));

    	$data = [
    		'data' => $gambar_encode
    	];

    	return response()->json($data);
    }
}

resources/views/gambar/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Konversi Gambar ke base64</div>
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form class="form-horizontal" role="form" id="gambar" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="gambar" class="col-md-4 control-label">Masukkan Gambar</label>

                            <div class="col-md-6">
                                <input id="gambar" type="file" class="form-control" name="gambar" value="" required autofocus>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary"> Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Hasil</div>
                <div class="panel-body">
                    <textarea class="form-control" id="hasil" rows="20" ></textarea>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footer')
<script type="text/javascript">
    $(document).on('submit', '#gambar', function(e){
          e.preventDefault();

          var form_data = new FormData($('#gambar')[0]);
          $.ajax({
              type:'POST',
              url:'{{ route('gambar.store') }}',
              processData: false,
              contentType: false,
              async: false,
              cache: false,
              data : form_data,
              success: function(response){
                $('#hasil').val(response.data);
              }
          });
        });
</script>
@endsection