routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// public

Route::get('/', function () {
    return view('welcome');
});

// user

Auth::routes();
Route::get('register/verify/{token}', 'Auth\RegisterController@verify'); 

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('/profile',['as' => 'profile', 'uses' => 'ProfileController@index']);
Route::get('/profile/edit',['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);

Route::get('/password',['as' => 'password.index', 'uses' => 'ProfileController@change']);
Route::post('/password',['as' => 'password.post', 'uses' => 'ProfileController@post']);


Route::resource('data', 'DataController');
Route::get('/getIndex',['as' => 'data.getIndex', 'uses' => 'DataController@getIndex']);

// Gambar to base64
Route::resource('gambar', 'GambarController');

app/Data.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Data extends Model
{
    protected $table = 'data';
    public static $rules = [
    'judul' 		=> 'min:3|required|unique:data',
    'keterangan'    =>'required',
    ];

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $guarded = ['id'];
	protected $hidden = ['id'];
	public $timestamps = true;

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	public function danger()
	{
		return encrypt($this->id);
	}
}

app/Http/Controllers/DataController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Data;
use Carbon\Carbon;
use Yajra\Datatables\Datatables;
use Validator;
use Illuminate\Support\Facades\Input;

class DataController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function getIndex()
    {

    	$data = Data::query()->orderBy('created_at','desc')->get();
    	return Datatables::of( $data )
                ->addColumn( 'action', function ( $data )
                    {
                        if (Auth::user()->hasRole('user')) {
                             $data = '';
                        }else{
                            $data = '<a href="'.route("data.edit",$data->danger()).'" class="btn btn-warning btn-xs" ><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a> <form action="'.route("data.destroy",$data->danger()).'" method="POST"><input type="hidden" name="_method" value="DELETE">'.csrf_field().'<button name="submit" class="btn btn-danger btn-xs" ><i class="fa fa-times" aria-hidden="true"></i> Delete</button></form>';
                        }
                       

                        return $data;
                    }
                )
                 ->editColumn('created_at', function(Data $data) {
                    return $data->created_at->diffForHumans();
                })
                ->addIndexColumn()
                ->make( TRUE );
    }

    public function create()
    {
        $data['title']  = "Buat Data";
        $data['users']   = Auth::user();
        return view('data.create')->with($data);
    }

    public function store(Request $request)
    {

    	$valid = Data::$rules;
        $validationCertificate  = Validator::make($request->all(), $valid);
        if ($validationCertificate->fails()) {
        	$this->throwValidationException($request, $validationCertificate);
        }

        $data =  Data::create([
        	'judul'			=> $request->judul,
        	'keterangan'	=> $request->keterangan
        	]);

        return redirect(route('home'))->with('status', 'Data Baru Berhasil Dibuat');
    }

    public function destroy($datum){

    	// delete
        $datum = decrypt($datum);
        Data::destroy($datum);

        return redirect(route('home'))->with('status', 'Data Berhasil Dihapus');
    }

    public function edit($datum){

        $datum = decrypt($datum);
    	$data['title']  = "Edit Data";
    	$data['data']	= Data::find($datum);
        $data['users']   = Auth::user();
        return view('data.edit')->with($data);
    }

    public function update(Request $request,$datum)
    {
        $datum = decrypt($datum);
    	$data = Data::$rules;
    	$data['judul'] = $data['judul'] . ',judul,' . $datum;
        $validationCertificate  = Validator::make($request->all(), $data);
        if ($validationCertificate->fails()) {
        	$this->throwValidationException($request, $validationCertificate);
        }

        $datas = Data::find($datum);
       	$datas->judul = $request->judul;
	    $datas->keterangan = $request->keterangan;
	    $datas->update();
        
        return redirect(route('home'))->with('status', 'Data Berhasil Diperbarui');
    }
}

resources/views/data/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $title or 'Coba' }}</div>
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form class="form-horizontal" role="form" method="POST" action="{{ route('data.store') }}" >
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                            <label for="judul" class="col-md-4 control-label">Judul</label>

                            <div class="col-md-6">
                                <input id="judul" type="text" class="form-control" name="judul" value="{{ old('judul') }}" required autofocus>

                                @if ($errors->has('judul'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('judul') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('keterangan') ? ' has-error' : '' }}">
                            <label for="keterangan" class="col-md-4 control-label">Keterangan</label>

                            <div class="col-md-6">
                                <textarea id="keterangan" class="form-control" name="keterangan" required>{{ old('keterangan') }}</textarea>

                                @if ($errors->has('keterangan'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('keterangan') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                   <i class="fa fa-plus" aria-hidden="true"></i> Tambah
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/data/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $title or 'Coba' }}</div>
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form class="form-horizontal" role="form" method="POST" action="{{ route('data.update',$data->danger()) }}" >
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">
                        <div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
                            <label for="judul" class="col-md-4 control-label">Judul</label>

                            <div class="col-md-6">
                                <input id="judul" type="text" class="form-control" name="judul" value="{{ $data->judul }}" required autofocus>

                                @if ($errors->has('judul'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('judul') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('keterangan') ? ' has-error' : '' }}">
                            <label for="keterangan" class="col-md-4 control-label">Keterangan</label>

                            <div class="col-md-6">
                                <textarea id="keterangan" class="form-control" name="keterangan" required>{{ $data->keterangan }}</textarea>

                                @if ($errors->has('keterangan'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('keterangan') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
 Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection