routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// public

Route::get('/', function () {
    return view('welcome');
});

// user

Auth::routes();
Route::get('register/verify/{token}', 'Auth\RegisterController@verify'); 

Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('/profile',['as' => 'profile', 'uses' => 'ProfileController@index']);
Route::get('/profile/edit',['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);
Route::put('/profile/store',['as' => 'profile.store', 'uses' => 'ProfileController@store']);

Route::get('/password',['as' => 'password.index', 'uses' => 'ProfileController@change']);
Route::post('/password',['as' => 'password.post', 'uses' => 'ProfileController@post']);


Route::resource('data', 'DataController');
Route::get('/getIndex',['as' => 'data.getIndex', 'uses' => 'DataController@getIndex']);

// Gambar to base64
Route::resource('gambar', 'GambarController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">

    <!-- font -->
    <link href='/css/font-awesome.min.css' rel='stylesheet' type='text/css'/> 

    @yield('head')

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
<header>
   <!-- navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a></li>
                            <li><a href="{{ url('/register') }}"><i class="fa fa-users" aria-hidden="true"></i> Register</a></li>
                        @else
                            <li><a href="{{ route('gambar.index') }}"> Konversi Gambar</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('profile') }}" ><i class="fa fa-user-circle-o" aria-hidden="true"></i> Profile</a>
                                    </li>
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="fa fa-sign-out" aria-hidden="true"></i> 
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
      </div>
    </nav>
</header>
<section class="section satu" id="dua"> 
    @yield('content')
</section>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
         
        window.setTimeout(function() {
            $(".alert").fadeTo(1000, 0).slideUp(1000, function(){
                $(this).remove(); 
            });
        }, 5000);
         
        });
    </script>
    @yield('footer')
</body>
</html>